### ISSUE TITLE
Symbol ♥ might crash the script from running on different operating systems

### ISSUE THREAD

**Issue by Snufkindee** [Midorina/PlaysTVPuller#1]
Tried to run the script and got an error referring to the ♥ symbol (\u2665) on playstvpuller.py. Removed it and the script worked perfectly after that. 

Suggesting to change it for example a typographical representation of a heart -> <3

Tried to create a pull request for this, but access is denied. So for anyone wondering why the script doesn't work then this might be a fix to your problem.

**Comment by Midorina** [comment]
Just fixed it. Thanks for the report.

I don't know why you can not create a pull request. If you know why, let me know and I'll also fix that.

**Comment by Snufkindee** [comment]
Not sure. Might be something on my side. Anycase thanks for the quick fix!
